# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-25 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NumericUserSearch',
            fields=[
                ('user_id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('user_search_id', models.IntegerField()),
                ('numeric_first_category', models.IntegerField(blank=True, db_index=True, null=True)),
                ('numeric_second_category', models.IntegerField(blank=True, null=True)),
                ('numeric_third_category', models.IntegerField(blank=True, null=True)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('product_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'numeric_user_search',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('first_category', models.IntegerField(blank=True, db_index=True, null=True)),
                ('second_category', models.IntegerField(blank=True, null=True)),
                ('third_category', models.IntegerField(blank=True, null=True)),
                ('product_code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'store_products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('address', models.TextField()),
            ],
        ),
    ]
